##---
# Source: etcd-operator/templates/operator-service-account.yaml

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: r1-etcd-operator-etcd-operator
  labels:
    chart: "etcd-operator-0.6.2"
    app: etcd-operator
    heritage: Tiller
    release: r1