##---
# Source: etcd-operator/templates/operator-clusterrole-binding.yaml

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: r1-etcd-operator-etcd-operator
  labels:
    chart: "etcd-operator-0.6.2"
    app: etcd-operator
    heritage: Tiller
    release: r1
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: r1-etcd-operator-etcd-operator
