apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy
  namespace: monitoring
data:
  Caddyfile: |
    :80
    log stdout
    errors stdout

    proxy / 127.0.0.1:9090 {
      header_upstream X-Forwarded-Proto {scheme}
      header_upstream X-Forwarded-Host {host}
      header_upstream Host {host}
    }

    jwt {
      path /
      redirect /login
      # allow sub webwurst
    }

    login {
      github client_id={$github_client_id},client_secret={$github_client_secret}
      success_url /
    }
