apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-core
  namespace: monitoring
  labels:
    app: prometheus
    component: core
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus-main
      labels:
        app: prometheus
        component: core
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: affinity/prometheus
                operator: In
                values:
                - "true"
      serviceAccountName: prometheus-k8s
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v1.7.1
        # image: quay.io/prometheus/prometheus:v2.0.0-beta.2
        imagePullPolicy: IfNotPresent
        args:
        # set storage.local.target-heap-size to 2/3 of physical memory:
        # 1.3*1024*1024*1024
        # set storage.local.retention in hours:
        # 30*24
        - "-config.file=/etc/prometheus/prometheus.yaml"
        - "-storage.local.target-heap-size=1395864371"
        - "-storage.local.retention=720h"
        - "-alertmanager.url=http://alertmanager:9093/"
        - "-storage.local.path=/prometheus"
        - "-web.console.libraries=/usr/share/prometheus/console_libraries"
        - "-web.console.templates=/usr/share/prometheus/consoles"
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 2
            memory: 2G
          limits:
            cpu: 2
            memory: 2G
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: rules
          mountPath: /etc/prometheus-rules
        - name: data
          mountPath: /prometheus
      - name: caddy
        image: giantswarm/caddy:0.10.4
        imagePullPolicy: IfNotPresent
        env:
        - name: github_client_id
          valueFrom:
            secretKeyRef:
              name: caddy
              key: github_client_id
        - name: github_client_secret
          valueFrom:
            secretKeyRef:
              name: caddy
              key: github_client_secret
        ports:
        - containerPort: 80
          name: caddy
          protocol: TCP
        volumeMounts:
        - name: caddy-config
          mountPath: /etc/caddy
      volumes:
      - name: caddy-config
        configMap:
          name: caddy
      - name: config
        configMap:
          name: prometheus-core
      - name: rules
        configMap:
          name: prometheus-rules
      - name: data
        hostPath:
          path: /srv/prometheus-data
