apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-auth
  labels:
    app: kibana-auth
    stack: logging
data:
  oauth2_proxy.cfg: |
    # for reference see https://github.com/bitly/oauth2_proxy/blob/master/contrib/oauth2_proxy.cfg.example

    http_address = "0.0.0.0:4180"
    upstreams = ["file:///dev/null"]

    provider = "github"
    email_domains = ["*"]
    github_org = "codeformuenster"
    github_team = "kube-admin,hacker"
    client_id = "16cf63d2612dc04c938f"
    client_secret = "e1ef428865fa6f05c6256d20a7bccdd027392fc2"
    cookie_secret = "vJsbnX5uFU0KY5OYa6a6gA=="
