apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: unims-scraper
  namespace: event-scraper-unims
spec:
  schedule: "0 0,12 * * *"
  #^ utc server-time
  startingDeadlineSeconds: 300
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: unims-scraper
            image: codeformuenster/event-scraper:0.1.3-1-unims
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
