apiVersion: batch/v1
kind: Job
metadata:
  name: unims-scraper
  namespace: event-scraper-unims
spec:
  template:
    spec:
      containers:
      - name: unims-scraper
        image: codeformuenster/event-scraper:0.1.3-1-unims
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
