##---
# Source: prometheus-operator/templates/create-servicemonitor-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: prometheus-operator
    chart: prometheus-operator-0.0.10
    heritage: Tiller
    release: r1
  name: r1-prometheus-operator-create-sm-job
spec:
  template:
    metadata:
      labels:
        app: prometheus-operator
        release: r1
      name: r1-prometheus-operator-create-sm-job
    spec:
      containers:
        - name: hyperkube
          image: "quay.io/coreos/hyperkube:v1.7.6_coreos.0"
          imagePullPolicy: "IfNotPresent"
          command:
            - ./kubectl
            - apply 
            - -f 
            - /tmp/servicemonitor/servicemonitor-operator.yaml
          volumeMounts:
            - mountPath: "/tmp/servicemonitor"
              name: tmp-configmap-servicemonitor
      volumes:
        - name: tmp-configmap-servicemonitor
          configMap:
            name: r1-prometheus-operator
      restartPolicy: OnFailure
      serviceAccountName: r1-prometheus-operator
