##---
# Source: prometheus-operator/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus-operator
    chart: prometheus-operator-0.0.10
    heritage: Tiller
    operator: prometheus
    release: r1
  name: r1-prometheus-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-operator
        operator: prometheus
        release: r1
    spec:
      containers:
        - name: prometheus-operator
          image: "quay.io/coreos/prometheus-operator:v0.15.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --kubelet-service=kube-system/kubelet
            - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.0.2
            - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
          ports:
            - containerPort: 8080
              name: http
          resources:
            {}
            
      serviceAccountName: r1-prometheus-operator
