##---
# Source: prometheus-operator/templates/get-crd-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: prometheus-operator
    chart: prometheus-operator-0.0.10
    heritage: Tiller
    release: r1
  name: r1-prometheus-operator-get-crd
spec:
  template:
    metadata:
      labels:
        app: prometheus-operator
        release: r1
      name: r1-prometheus-operator-get-crd
    spec:
      containers:
        - name: hyperkube
          image: "quay.io/coreos/hyperkube:v1.7.6_coreos.0"
          imagePullPolicy: "IfNotPresent"
          command:
            - ./kubectl
            - get
            - customresourcedefinitions
            - alertmanagers.monitoring.coreos.com
            - prometheuses.monitoring.coreos.com
            - servicemonitors.monitoring.coreos.com
      restartPolicy: OnFailure
      serviceAccountName: r1-prometheus-operator
