##---
# Source: prometheus-operator/templates/servicemonitor-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: r1-prometheus-operator
data:
  servicemonitor-operator.yaml: |-
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        labels:
          app: prometheus-operator
          chart: "prometheus-operator-0.0.10"
          heritage: "Tiller"
          release: "r1"
          prometheus: r1
        name: prometheus-operator
      spec:
        jobLabel: prometheus-operator
        selector:
          matchLabels:
        selector:
          matchLabels:
            operated-prometheus: "true"
        namespaceSelector:
          matchNames:
            - "default"
        endpoints:
        - port: http
          interval: 30s