apiVersion: v1
kind: Service
metadata:
  name: nominatim-server
  namespace: nominatim
  labels:
    app: nominatim
    component: server
spec:
  ports:
  - port: 80
    protocol: TCP
    # targetPort: ui
    targetPort: 80
  selector:
    app: nominatim
    component: server
