apiVersion: v1
kind: ConfigMap
metadata:
  # name: ingress-controller-config-template
  # namespace: ingress
  # labels:
  #   k8s-app: ingress-controller
  #   component: config-template
data:
  traefic.toml: |
    logLevel = "DEBUG"
    defaultEntryPoints = ["http", "https"]

    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/etc/traefik/server.crt"
          KeyFile = "/etc/traefik/server.key"
      [entryPoints.https2]
      address = ":8443"
        [entryPoints.https2.tls]
          [[entryPoints.https2.tls.certificates]]
          CertFile = "/etc/traefik/server.crt"
          KeyFile = "/etc/traefik/server.key"
        [entryPoints.https2.auth.basic]
        users = [ "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/" ]

    [web]
    address = ":6443"
    CertFile = "/etc/traefik/server.crt"
    KeyFile = "/etc/traefik/server.key"
    ReadOnly = true
      [web.auth.basic]
      users = [ "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/" ]

    [file]
    filename = "/etc/traefik/rules.toml"
    watch = true
