apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-main
  namespace: monitoring
  labels:
    app: prometheus
    component: main
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus-main
      labels:
        app: prometheus
        component: main
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  {
                    "matchExpressions": [
                      {
                        "key": "affinity/prometheus",
                        "operator": "In",
                        "values": ["true"]
                      }
                    ]
                  }
                ]
              }
            }
          }
    spec:
      containers:
      - name: prometheus-main
        image: prom/prometheus:v1.3.1
        args:
        - '-storage.local.memory-chunks=400000'
        - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 500m
            memory: 500M
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus-main
      - name: prometheus-data
        hostPath:
          path: /srv/prometheus-data
