apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: curator
  namespace: monitoring
spec:
  schedule: "19 0 * * *"
  #^ utc server-time
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: bobrik/curator:4.2.6
            args: ["--config", "/etc/curator/config.yml", "/etc/curator/action_file.yml"]
            volumeMounts:
              - name: config
                mountPath: /etc/curator
          volumes:
            - name: config
              configMap:
                name: curator
          restartPolicy: OnFailure
