apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: anaconda-jupyter
  namespace: anaconda-jupyter
  labels:
    app: anaconda-jupyter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: anaconda-jupyter
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  {
                    "matchExpressions": [
                      {
                        "key": "anaconda",
                        "operator": "In",
                        "values": ["yes"]
                      }
                    ]
                  }
                ]
              }
            }
          }
    spec:
      containers:
      - name: anaconda-jupyter
        image: codeformuenster/anaconda-test:r3
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c
          - |
            /opt/conda/bin/jupyter notebook \
              --notebook-dir=/opt/notebooks \
              --ip='*' \
              --port=8888 \
              --no-browser
        # command:
        #   - /bin/bash
        #   - -c
        #   - |
        #     /opt/conda/bin/conda install jupyter -y --quiet \
        #       && mkdir --parents /opt/notebooks \
        #       && /opt/conda/bin/jupyter notebook \
        #         --notebook-dir=/opt/notebooks \
        #         --ip='*' \
        #         --port=8888 \
        #         --no-browser
        # resources:
        #   # keep request = limit to keep this container in guaranteed class
        #   limits:
        #     cpu: 100m
        #   requests:
        #     cpu: 100m
        ports:
        - containerPort: 8888
          name: ui
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/notebooks
          name: anaconda-volume
      volumes:
      - name: anaconda-volume
        hostPath:
          # directory location on host
          path: /srv/anaconda-volume
