# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     ingress.kubernetes.io/auth-signin: https://$host/oauth2/sign_in
#     ingress.kubernetes.io/auth-signin: https://oauth.codeformuenster.org/sign_in ?
#     ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
#   name: external-auth-oauth2
#   namespace: kube-system
# spec:
#   rules:
#   - host: dashboard.codeformuenster.org
#     http:
#       paths:
#       - backend:
#           serviceName: kubernetes-dashboard
#           servicePort: 80
#         path: /
