apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-apply
  namespace: kube-apply
  labels:
    app: kube-apply
spec:
  template:
    metadata:
      labels:
        app: kube-apply
    spec:
      containers:
      - name: kube-apply
        image: codeformuenster/kube-apply:0.1.2
        volumeMounts:
        - name: config
          mountPath: /etc/caddy
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: kube-apply
