apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: parkleit-fetcher
  namespace: parkleit-api
spec:
  schedule: "*/5 * * * *"
  #^ utc server-time
  startingDeadlineSeconds: 300
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          # FIXME use elasticsearch-python-api for this
          containers:
          - name: parkleit-fetcher
            image: webwurst/curl-utils
            imagePullPolicy: IfNotPresent
            command:
            - sh
            - -c
            args:
            - curl -sSf parkleit-api:5000/minio
          restartPolicy: OnFailure
