apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: parkleit-api
  namespace: default
  labels:
    app: parkleit-api
spec:
  replicas: 1
  template:
    metadata:
      name: parkleit-api
      labels:
        app: parkleit-api
    spec:
      containers:
      - name: parkleit-api
        image: codeformuenster/parkleit-scraper
        ports:
        - name: api
          containerPort: 5000
